bundler_args: --without development
before_install: gem install bundler
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: 1.8.7
    - rvm: rbx-2
  fast_finish: true
sudo: false
