bundler_args: --without development
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: 2.2.4
      gemfile: Gemfile.rack2
    - rvm: 2.3.0
      gemfile: Gemfile.rack2
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
